# Generated by Django 5.1.15 on 2026-05-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('recognizing', 'Розпізнається'), ('needs_mapping', 'Потрібен маппінг'), ('ready', 'Готовий до генерації'), ('xlsx_ready', 'Excel згенеровано'), ('error', 'Помилка')], default='draft', max_length=20)),
                ('xlsx_url', models.URLField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognized_sku', models.CharField(max_length=255)),
                ('recognized_name', models.CharField(blank=True, max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('match_status', models.CharField(choices=[('auto', 'Авто'), ('manual', 'Вручну'), ('unmapped', 'Не знайдено')], default='unmapped', max_length=10)),
                ('raw_ocr_json', models.JSONField(blank=True, null=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='catalog.ourproduct')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='receipts.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('image_url', models.URLField(blank=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='receipts.receipt')),
            ],
        ),
    ]
