# Generated by Django 5.1.15 on 2026-05-30 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
        ('suppliers', '0002_supplier_edrpou'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='recognized_supplier',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='suppliers.supplier'),
        ),
    ]
