# Generated by Django 5.1.15 on 2026-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesdrive_id', models.CharField(max_length=255, unique=True)),
                ('sku', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
