# Generated by Django 5.1.15 on 2026-05-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='edrpou',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
