"""Migrations package for the suppliers app.

Migration modules are generated by ``python manage.py makemigrations`` and are
intentionally not hand-written here. This file only marks the directory as a
Python package so Django can discover migrations.
"""

from __future__ import annotations
