# Generated by Django 5.1.15 on 2026-05-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(max_length=255)),
                ('supplier_sku_normalized', models.CharField(db_index=True, max_length=255)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('our_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='catalog.ourproduct')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='suppliers.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'supplier_sku_normalized')},
            },
        ),
    ]
